# Generated by Django 6.0.4 on 2026-04-19 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.IntegerField(help_text='Score 1-100')),
                ('technical_skills', models.IntegerField(help_text='Score 1-100')),
                ('communication', models.IntegerField(help_text='Score 1-100')),
                ('teamwork', models.IntegerField(help_text='Score 1-100')),
                ('initiative', models.IntegerField(help_text='Score 1-100')),
                ('overall_score', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=5)),
                ('comments', models.TextField(blank=True)),
                ('recommended', models.BooleanField(default=False, help_text='Would you recommend this student?')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Applications.placement')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_gained', to='Applications.placement')),
            ],
        ),
    ]
