# Generated by Django 6.0.4 on 2026-04-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_universityadminprofile'),
         
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='List the requirements for the internship, separated by commas.')),
                ('location', models.CharField(max_length=255)),
                ('occupation', models.CharField(choices=[('IT', 'Information Technology'), ('SD', 'Software Development'), ('DS', 'Data Science'), ('CS', 'Cybersecurity'), ('WD', 'Web Development'), ('AI', 'Artificial Intelligence'), ('ACC', 'Accounting'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('HR', 'Human Resources'), ('BA', 'Business Administration'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('GD', 'Graphic Design'), ('MED', 'Medicine/Healthcare'), ('NUR', 'Nursing'), ('LAW', 'Law/Legal'), ('EDU', 'Education'), ('JRN', 'Journalism'), ('Other', 'Other')], help_text='Field or domain of the internship.', max_length=50)),
                ('internship_type', models.CharField(choices=[('Academic', 'Academic'), ('Professional', 'Professional')], help_text='Academic or Professional internship.', max_length=20)),
                ('duration', models.CharField(help_text='e.g., 3 months, 6 months.', max_length=255)),
                ('start_date', models.DateField(help_text='The date when the internship starts.')),
                ('end_date', models.DateField(help_text='The date when the internship ends.')),
                ('deadline', models.DateField(help_text='The last date to apply for the internship.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed'), ('Canceled', 'Canceled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_posts', to='accounts.organizationprofile')),
            ],
        ),
    ]
