# Generated by Django 6.0.4 on 2026-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippost',
            name='slots',
            field=models.PositiveIntegerField(default=1, help_text='Number of available positions.'),
        ),
    ]
