# Generated by Django 6.0.4 on 2026-04-15 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
